; Auto-generated. Do not edit!


(cl:in-package turtlebot3_move-msg)


;//! \htmlinclude OdomRecordGoal.msg.html

(cl:defclass <OdomRecordGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass OdomRecordGoal (<OdomRecordGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OdomRecordGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OdomRecordGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot3_move-msg:<OdomRecordGoal> is deprecated: use turtlebot3_move-msg:OdomRecordGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OdomRecordGoal>) ostream)
  "Serializes a message object of type '<OdomRecordGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OdomRecordGoal>) istream)
  "Deserializes a message object of type '<OdomRecordGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OdomRecordGoal>)))
  "Returns string type for a message object of type '<OdomRecordGoal>"
  "turtlebot3_move/OdomRecordGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OdomRecordGoal)))
  "Returns string type for a message object of type 'OdomRecordGoal"
  "turtlebot3_move/OdomRecordGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OdomRecordGoal>)))
  "Returns md5sum for a message object of type '<OdomRecordGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OdomRecordGoal)))
  "Returns md5sum for a message object of type 'OdomRecordGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OdomRecordGoal>)))
  "Returns full string definition for message of type '<OdomRecordGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OdomRecordGoal)))
  "Returns full string definition for message of type 'OdomRecordGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OdomRecordGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OdomRecordGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'OdomRecordGoal
))
