; Auto-generated. Do not edit!


(cl:in-package turtlebot3_move-msg)


;//! \htmlinclude OdomRecordFeedback.msg.html

(cl:defclass <OdomRecordFeedback> (roslisp-msg-protocol:ros-message)
  ((current_total
    :reader current_total
    :initarg :current_total
    :type cl:float
    :initform 0.0))
)

(cl:defclass OdomRecordFeedback (<OdomRecordFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OdomRecordFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OdomRecordFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name turtlebot3_move-msg:<OdomRecordFeedback> is deprecated: use turtlebot3_move-msg:OdomRecordFeedback instead.")))

(cl:ensure-generic-function 'current_total-val :lambda-list '(m))
(cl:defmethod current_total-val ((m <OdomRecordFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader turtlebot3_move-msg:current_total-val is deprecated.  Use turtlebot3_move-msg:current_total instead.")
  (current_total m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OdomRecordFeedback>) ostream)
  "Serializes a message object of type '<OdomRecordFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_total))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OdomRecordFeedback>) istream)
  "Deserializes a message object of type '<OdomRecordFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_total) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OdomRecordFeedback>)))
  "Returns string type for a message object of type '<OdomRecordFeedback>"
  "turtlebot3_move/OdomRecordFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OdomRecordFeedback)))
  "Returns string type for a message object of type 'OdomRecordFeedback"
  "turtlebot3_move/OdomRecordFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OdomRecordFeedback>)))
  "Returns md5sum for a message object of type '<OdomRecordFeedback>"
  "30966342c24c9732e6e891bbe67686ec")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OdomRecordFeedback)))
  "Returns md5sum for a message object of type 'OdomRecordFeedback"
  "30966342c24c9732e6e891bbe67686ec")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OdomRecordFeedback>)))
  "Returns full string definition for message of type '<OdomRecordFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 current_total~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OdomRecordFeedback)))
  "Returns full string definition for message of type 'OdomRecordFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 current_total~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OdomRecordFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OdomRecordFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'OdomRecordFeedback
    (cl:cons ':current_total (current_total msg))
))
