// Generated by gencpp from file turtlebot3_move/FindWallResponse.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MOVE_MESSAGE_FINDWALLRESPONSE_H
#define TURTLEBOT3_MOVE_MESSAGE_FINDWALLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_move
{
template <class ContainerAllocator>
struct FindWallResponse_
{
  typedef FindWallResponse_<ContainerAllocator> Type;

  FindWallResponse_()
    : wallfound(false)  {
    }
  FindWallResponse_(const ContainerAllocator& _alloc)
    : wallfound(false)  {
  (void)_alloc;
    }



   typedef uint8_t _wallfound_type;
  _wallfound_type wallfound;





  typedef boost::shared_ptr< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FindWallResponse_

typedef ::turtlebot3_move::FindWallResponse_<std::allocator<void> > FindWallResponse;

typedef boost::shared_ptr< ::turtlebot3_move::FindWallResponse > FindWallResponsePtr;
typedef boost::shared_ptr< ::turtlebot3_move::FindWallResponse const> FindWallResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_move::FindWallResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtlebot3_move::FindWallResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_move::FindWallResponse_<ContainerAllocator2> & rhs)
{
  return lhs.wallfound == rhs.wallfound;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtlebot3_move::FindWallResponse_<ContainerAllocator1> & lhs, const ::turtlebot3_move::FindWallResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtlebot3_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66229cd821efb4126c80f35757f3c73e";
  }

  static const char* value(const ::turtlebot3_move::FindWallResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66229cd821efb412ULL;
  static const uint64_t static_value2 = 0x6c80f35757f3c73eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_move/FindWallResponse";
  }

  static const char* value(const ::turtlebot3_move::FindWallResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool wallfound\n"
;
  }

  static const char* value(const ::turtlebot3_move::FindWallResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wallfound);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindWallResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_move::FindWallResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_move::FindWallResponse_<ContainerAllocator>& v)
  {
    s << indent << "wallfound: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.wallfound);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_MOVE_MESSAGE_FINDWALLRESPONSE_H
