// Generated by gencpp from file turtlebot3_move/FindWallRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_MOVE_MESSAGE_FINDWALLREQUEST_H
#define TURTLEBOT3_MOVE_MESSAGE_FINDWALLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_move
{
template <class ContainerAllocator>
struct FindWallRequest_
{
  typedef FindWallRequest_<ContainerAllocator> Type;

  FindWallRequest_()
    {
    }
  FindWallRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FindWallRequest_

typedef ::turtlebot3_move::FindWallRequest_<std::allocator<void> > FindWallRequest;

typedef boost::shared_ptr< ::turtlebot3_move::FindWallRequest > FindWallRequestPtr;
typedef boost::shared_ptr< ::turtlebot3_move::FindWallRequest const> FindWallRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_move::FindWallRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace turtlebot3_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::turtlebot3_move::FindWallRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_move/FindWallRequest";
  }

  static const char* value(const ::turtlebot3_move::FindWallRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::turtlebot3_move::FindWallRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FindWallRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_move::FindWallRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::turtlebot3_move::FindWallRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_MOVE_MESSAGE_FINDWALLREQUEST_H
